preload = /home/klaasjan/Pictures/Wallpapers/custom/nixos_01.jpg
preload = /home/klaasjan/Pictures/Wallpapers/custom/abstract_01.jpg

wallpaper {
    monitor = 
    path = /home/klaasjan/Pictures/Wallpapers/custom/abstract_01.jpg
    fit_mode = cover
}

# Extra configuration:
splash = true
# ToCheck: when the splash_offset feature for hyprpaper is merged with the stable ranch
# splash_offset = 50




