$base0B = rgba(A3BE8Cff) #A3BE8C
$base0C = rgba(88C0D0ff) #88C0D0
$base0D = rgba(81A1C1ff) #81A1C1
$base0E = rgba(B48EADff) #B48EAD

general {
  disable_loading_bar = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 2
    brightness = 0.5
}

shape {
    monitor =
    size = 650, 25
    rounding = -1
    border_size = 1
    border_color = $base0C
    rotate = 0
    xray = true

    position = 0, -13
    halign = center
    valign = top
}

image {
    monitor =
    path = /home/klaasjan/Pictures/tux.png
    size = 200
    rounding = -1
    border_size = 5
    border_color = $base0C
    rotate = 0
    reload_time = -1 # seconds between reloading, 0 to reload with SIGUSR2
    reload_cmd =  # command to get new path. if empty, old path will be used. don't run "follow" commands like tail -F

    shadow_passes = 3
    shadow_size = 10
    shadow_color = $base0C
    shadow_boost = 4

    position = 0, 200
    halign = center
    valign = center
}


input-field {
    monitor =
    size = 200, 50
    outline_thickness = 5
    dots_size = 0.33 # Scale of input-field height, 0.2 - 0.8
    dots_spacing = 0.15 # Scale of dots' absolute size, 0.0 - 1.0
    dots_center = true
    dots_rounding = 1 # -1 default circle, -2 follow input-field rounding
    outer_color = $base0D
    inner_color = $base0C
    font_color = $base0D
    fade_on_empty = true
    fade_timeout = 1000 # Milliseconds before fade_on_empty is triggered.
    placeholder_text = <i>Password...</i> # Text rendered in the input box when it's empty.
    hide_input = false
    rounding = -1 # -1 means complete rounding (circle/oval)
    check_color = $base0B
    fail_color = $base0E
    fail_text = 
    fail_transition = 300
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false

    position = 0, 20
    halign = center
    valign = bottom
}

label {
    monitor =
    text = $TIME
    text_align = center
    color = $base0C
    font_size = 35
    font_family = Fira Sans
    rotate = 0

    position = 0, 0
    halign = center
    valign = center
}

label {
    monitor =
    text = $ATTEMPTS
    text_align = center
    color = $base0E
    font_size = 15
    font_family = Fira Code

    position = 0, 0
    halign = left
    valign = bottom
}
